version: '3.8'

services:

  frontend:
    build: frontend
    container_name: bank-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=localhost

  backend:
    build: backend
    container_name: bank-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ExB3RYfeCMINW2
      - MYSQL_DB=bank_app

  db:
    image: mysql:lts
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ExB3RYfeCMINW2
      MYSQL_DATABASE: bank_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./bank_db.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  mysql-data: